# Generated by Django 4.2.2 on 2023-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inscription',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
